require: rubocop-rspec

LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/AbcSize:
  Max: 20

# Rely on AbcSize
MethodLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

# TODO: Fix these
RSpec/NamedSubject:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
# TODO: And maybe this
RSpec/AnyInstance:
  Enabled: false
